### ISSUE TITLE
add: set_repos()

### ISSUE THREAD

**Issue by kalimu** [r-world-devs/GitAI#2]
- [ ] wrapper for GitStats
- [ ] creates GitStats object and adds it to the GitAIProject as active binding

**Comment by maciekbanas** [comment]
@kalimu wonder how we want to pass repos:
- with two separate `host` parameter and `repos` (as full names with org/repo),
- as full web urls (one parameter).

What is your opinion?

**Comment by maciekbanas** [comment]
As I am thinking more about this: I think if we want adjust it to GitHub and GitLab, I would go for two separate functions: `set_github_repos()` and `set_gitlab_repos()`. This would nicely mirror GitStats' `set_github_host()` and `set_gitlab_host()`.
