### ISSUE TITLE
add: process_repos() with minimal workflow

### ISSUE THREAD

**Issue by kalimu** [r-world-devs/GitAI#6]
- [x] GitStats: get repos metadata
- [x] GitStats: get repos files
- [x] GitStats: get files content
- [x] iterate: process_repo()
    - [x] process_content()
    - [x] return output
- [ ] return: prompting results with repo metadata

**Comment by maciekbanas** [comment]
@kalimu Do I get it correctly that above GitStats functions (`get_files_content()`, `get_repos()`, `get_files_structure()`) should be wrapped by `process_repo()`?

**Comment by kalimu** [comment]
We are not returning repos metadata together with processed content yet. Not sure what we should return though. Repo URL for sure,...

**Comment by maciekbanas** [comment]
> We are not returning repos metadata together with processed content yet. Not sure what we should return though. Repo URL for sure,... maybe also what files what used to generate the output. Any thoughts @maciekbanas ?

Nothing special... repos URLs and used files should do the job for now. Maybe in future we will see what we need (timestamps, ids, authors, repo type, etc.). I would stay minimal for the time being, let's add what we see now is crucial.
